name: macOS Image Builder

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 1 * *'  # Run monthly on the 1st

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          # - macos_version: "15"
          #   macos_name: "sequoia"
          #   catalog: "publicrelease"
          # - macos_version: "14"
          #   macos_name: "sonoma"
          # - macos_version: "13"
          #   macos_name: "ventura"
          # - macos_version: "12"
          #   macos_name: "monterey"
          - macos_version: "10.16"
            macos_name: "big_sur"
            catalog: "publicrelease"
          # - macos_version: "10.15"
          #   macos_name: "catalina"
          # - macos_version: "10.14"
          #   macos_name: "mojave"
          # - macos_version: "10.13"
          #   macos_name: "high_sierra"
          # - macos_version: "10.12"
          #   macos_name: "sierra"
          # - macos_version: "10.11"
          #   macos_name: "el_capitan"
          # - macos_version: "10.10"
          #   macos_name: "yosemite"
          # - macos_version: "10.9"
          #   macos_name: "mavericks"
          # - macos_version: "10.8"
          #   macos_name: "mountain_lion"
          # - macos_version: "10.7"
          #   macos_name: "lion"
          # - macos_version: "10.6"
          #   macos_name: "snow_leopard"
          # - macos_version: "10.5"
          #   macos_name: "leopard"
          # - macos_version: "10.4"
          #   macos_name: "tiger"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Dependencies
        run: |
          brew install coreutils git
    
      - name: Clone and Setup gibMacOS
        run: |
          git clone https://github.com/corpnewt/gibMacOS.git
          cd gibMacOS
          python -m venv .venv
          source .venv/bin/activate
          pip install pyyaml requests
          chmod +x gibMacOS.command
        # 保证后续所有脚本都能使用虚拟环境里的工具
        env:
          PATH: ${{ github.workspace }}/gibMacOS/.venv/bin:${{ env.PATH }}
    
      - name: Build Full macOS DMG with gibMacOS
        working-directory: ${{ github.workspace }}/gibMacOS
        run: |
          source .venv/bin/activate
          # -b 后面跟你的版本简称（如 Sequoia、Monterey 等）
          # -d 后面跟输出目录，这里指向 repo 根目录下的 output
          ./gibMacOS.command --no-interactive \
                            --catalog ${{ matrix.catalog || 'publicrelease' }} \
                            --maxos ${{ matrix.macos_version }} \
                            -b ${{ matrix.macos_name }} \
                            -d "${{ github.workspace }}/output"
    
      - name: List Output
        run: |
          ls -lh ${{ github.workspace }}/output
    
              
      - name: Create Release Notes and Push to Repository
        working-directory: ${{ github.workspace }}
        run: |
          MACOS_NAME="${{ matrix.macos_name }}"
          MACOS_VERSION="${{ matrix.macos_version }}"
          if [ ! -f "$GITHUB_WORKSPACE/output/${MACOS_NAME}_full.dmg" ]; then
            echo "Warning: Output file not found!"
            exit 1
          fi
          echo "# macOS Installation Image - $MACOS_NAME ($MACOS_VERSION)" > "$GITHUB_WORKSPACE/output/release_notes.txt"
          echo "" >> "$GITHUB_WORKSPACE/output/release_notes.txt"
          echo "This is an automatically built complete macOS installation image." >> "$GITHUB_WORKSPACE/output/release_notes.txt"
          echo "" >> "$GITHUB_WORKSPACE/output/release_notes.txt"
          echo "## Usage" >> "$GITHUB_WORKSPACE/output/release_notes.txt"
          echo "" >> "$GITHUB_WORKSPACE/output/release_notes.txt"
          echo "1. Download the complete DMG file" >> "$GITHUB_WORKSPACE/output/release_notes.txt"
          echo "2. Use Disk Utility or other tools to write the DMG to a USB drive" >> "$GITHUB_WORKSPACE/output/release_notes.txt"
          echo "" >> "$GITHUB_WORKSPACE/output/release_notes.txt"
          echo "## Build Information" >> "$GITHUB_WORKSPACE/output/release_notes.txt"
          echo "" >> "$GITHUB_WORKSPACE/output/release_notes.txt"
          echo "- Build Date: $(date '+%Y-%m-%d %H:%M:%S')" >> "$GITHUB_WORKSPACE/output/release_notes.txt"
          echo "- GitHub Action Run: $GITHUB_RUN_ID" >> "$GITHUB_WORKSPACE/output/release_notes.txt"
          echo "- Image Name: ${MACOS_NAME}" >> "$GITHUB_WORKSPACE/output/release_notes.txt"
          echo "- macOS Version: ${MACOS_VERSION}" >> "$GITHUB_WORKSPACE/output/release_notes.txt"
          TEMP_REPO_DIR="$GITHUB_WORKSPACE/temp_repo"
          mkdir -p "$TEMP_REPO_DIR"
          cd "$TEMP_REPO_DIR"
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote add origin https://cnb:${{ secrets.GIT_TOKEN }}@cnb.cool/oneclickvirt/template.git
          git fetch origin
          if git ls-remote --heads origin ${{ matrix.macos_name }}-build | grep -q ${{ matrix.macos_name }}-build; then
            git checkout -b ${{ matrix.macos_name }}-build origin/${{ matrix.macos_name }}-build
          else
            git checkout --orphan ${{ matrix.macos_name }}-build
            # Clear working directory when creating new branch
            git rm -rf . || true
          fi
          mkdir -p "$TEMP_REPO_DIR/macOS-images/$MACOS_NAME"
          cp -f "$GITHUB_WORKSPACE/output/${MACOS_NAME}_full.dmg" "$TEMP_REPO_DIR/macOS-images/$MACOS_NAME/"
          cp -f "$GITHUB_WORKSPACE/output/release_notes.txt" "$TEMP_REPO_DIR/macOS-images/$MACOS_NAME/"
          git add "$TEMP_REPO_DIR/macOS-images/$MACOS_NAME/"*
          git commit -m "Add macOS $MACOS_NAME ($MACOS_VERSION) installation image"
          git push -u origin ${{ matrix.macos_name }}-build:${{ matrix.macos_name }}-build
